### ISSUE TITLE
Where is hmpps-auth being set as the Authorization Server?

### ISSUE THREAD

**Issue by deduper** [ministryofjustice/prison-api#910]
How does the prison-api specify [_hmpps-auth_](https://github.com/ministryofjustice/hmpps-auth) as its OAuth 2.0  authorization server? Where exactly in the code or configuration files I mean?

Or if you're doing it by Spring Security's auto-configuration, can you share a link to the Spring Security documentation that describes that auto-configuration? Please? I've Googled. But I couldn't find anything.

I'm aware of a few different ways provided by Spring Security for a resource server to configure what authorization server it will delegate OAuth 2.0 authorization to.

* [_Specify it in application.yaml_](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#specifying-the-authorization-server) (_or application.properties_):

```
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.example.com/issuer
```

* [_Specify it using the DSL_](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#oauth2resourceserver-jwt-jwkseturi-dsl):

```
@EnableWebSecurity
public class DirectlyConfiguredJwkSetUri extends WebSecurityConfigurerAdapter {
    protected void configure(HttpSecurity http) {
        http
            .authorizeRequests(authorize -> authorize
                .anyRequest().authenticated()
            )
            .oauth2ResourceServer(oauth2 -> oauth2
                .jwt(jwt -> jwt
                    .jwkSetUri("https://idp.example.com/.well-known/jwks.json")
                )
            );
    }
}
```

I can't see anywhere in any prison-api file where the authorization server is set. Apart from [_this dev profile configurations_](https://github.com/ministryofjustice/prison-api/blob/main/src/main/resources/application-dev.yml#L6) I found in the project:

```
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub
```

[_And this test resource_](https://github.com/ministryofjustice/prison-api/blob/main/src/test/resources/application-test-jwk.yml):

```
spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://localhost:9090/auth/.well-known/jwks.json
```

Thank you in advance.
